server:
  port: 8081
spring:
    application:
        name: pc-common-common
    datasource:
      druid:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.0.157:7890/common_frame?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2b8&useSSL=false&allowPublicKeyRetrieval=true&autoReconnect=true&failOverReadOnly=false&rewriteBatchedStatements=true
        username: comuser
        password: 123456
    cloud:
       nacos:
         discovery:
            register-enabled: false #开发环境不注册到nacos